Merge students.csv and scores.csv on sudent)id
Average score per subject with groupby
Average score per city(needs the erge first)
Filter L Which student scored >90 in any subject

In [1]:
import pandas as pd
import numpy as np

In [3]:
#Merge students.csv and scores.csv on sudent)id
df1 = pd.read_csv('students.csv')
df2 = pd.read_csv('scores.csv')
df = pd.merge(df1,df2,on = "student_id")
df

    student_id      name        city   subject  score
0            1     Alice   Kathmandu      Math     95
1            1     Alice   Kathmandu   Science     88
2            2       Bob     Pokhara      Math     76
3            2       Bob     Pokhara   English     82
4            3   Charlie   Kathmandu   Science     91
5            3   Charlie   Kathmandu      Math     89
6            4     David      Butwal   English     67
7            4     David      Butwal   Science     72
8            5      Emma     Pokhara      Math     98
9            5      Emma     Pokhara  Computer     93
10           6     Frank  Biratnagar  Computer     85
11           6     Frank  Biratnagar      Math     78
12           7     Grace      Butwal   Science     90
13           7     Grace      Butwal   English     86
14           8     Henry   Kathmandu  Computer     94
15           8     Henry   Kathmandu      Math     81
16           9  Isabella  Biratnagar   English     79
17           9  Isabella  Biratnagar   Science     87
18          10      Jack     Pokhara      Math     92
19          10      Jack     Pokhara  Computer     88

In [4]:
#Average score per subject with goupby
df.groupby("subject")['score'].mean()

subject
Computer    90.0
English     78.5
Math        87.0
Science     85.6
Name: score, dtype: float64

In [9]:
#Average score per city(needs the merge first)
df.groupby("city")['score'].mean()

city
Biratnagar    82.250000
Butwal        78.750000
Kathmandu     89.666667
Pokhara       88.166667
Name: score, dtype: float64

In [11]:
#Filter L Which student scored >90 in any subject

df[df['score']>90]

    student_id     name       city   subject  score
0            1    Alice  Kathmandu      Math     95
4            3  Charlie  Kathmandu   Science     91
8            5     Emma    Pokhara      Math     98
9            5     Emma    Pokhara  Computer     93
14           8    Henry  Kathmandu  Computer     94
18          10     Jack    Pokhara      Math     92

In [4]:
df = df.sort_values(by ='city',ascending = True)
len(df)

    student_id      name        city   subject  score
17           9  Isabella  Biratnagar   Science     87
16           9  Isabella  Biratnagar   English     79
10           6     Frank  Biratnagar  Computer     85
11           6     Frank  Biratnagar      Math     78
6            4     David      Butwal   English     67
7            4     David      Butwal   Science     72
12           7     Grace      Butwal   Science     90
13           7     Grace      Butwal   English     86
0            1     Alice   Kathmandu      Math     95
1            1     Alice   Kathmandu   Science     88
4            3   Charlie   Kathmandu   Science     91
5            3   Charlie   Kathmandu      Math     89
15           8     Henry   Kathmandu      Math     81
14           8     Henry   Kathmandu  Computer     94
9            5      Emma     Pokhara  Computer     93
8            5      Emma     Pokhara      Math     98
3            2       Bob     Pokhara   English     82
2            2       Bob     Pokhara      Math     76
18          10      Jack     Pokhara      Math     92
19          10      Jack     Pokhara  Computer     88

In [5]:
df.to_csv('city_group.csv',index = False)

In [6]:
df['student_id'].nunique()

10